import Header from '@/components/Header';
import './globals.css';

export const metadata = {
  title: {
    template: "%s - Yamato's Portfolio",
    default: "Yamato's Portfolio",
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="color-primary">
        <Header />
        {children}
      </body>
    </html>
  );
}
