import Header from '@/components/Header';
import './globals.css';
import { Montserrat } from 'next/font/google';
import { Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata = {
  title: {
    template: "%s - Yamato's Portfolio",
    default: "Yamato's Portfolio",
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className="">
      <body className={`${montserrat.className}`}>
        <Theme>
          <Header />
          {children}
        </Theme>
      </body>
    </html>
  );
}
